global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'default-receiver'
    # For now, just log to console; we will add email/Slack config here later