global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'montahabenjabalah@gmail.com'
  smtp_auth_username: 'montahabenjabalah@gmail.com'
  smtp_auth_password: 'bjhrbrtomwxgdxxs
'

route:
  receiver: 'email'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email'
    email_configs:
      - to: 'montaha.benjaballah@esprit.tn'
        send_resolved: true