# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files (optional)
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Jenkins
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["172.25.123.208:8082"]

  # Ubuntu machine (Node Exporter, updated to use host IP)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["172.25.123.208:9100"]

  # Spring application (via Spring Actuator)
  - job_name: "spring-app"
    metrics_path: "/foyer/actuator/prometheus"
    static_configs:
      - targets: ["172.25.123.208:8089""]

  # MySQL database (via MySQL Exporter)
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]