# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Règles d'alerte
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Jenkins
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["172.25.123.208:8082"]

  # Node Exporter (sur la machine Ubuntu)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["172.25.123.208:9100"]

  # Application Spring Boot
  - job_name: "spring-app"
    metrics_path: "/foyer/actuator/prometheus"
    static_configs:
      - targets: ["172.25.123.208:8089"]

  # Exporter MySQL
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]